# -*- coding: utf-8 -*-
"""Copy of Deep Learning 13Sep2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUry39tMDNCqFN7ehpYjO0wRO8QkNNTh
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score

# load the dataset
from google.colab import drive
drive.mount('/content/drive')  # Mount Google Drive
df = pd.read_csv('/content/drive/My Drive/data/test.csv')

#df = pd.read_csv('test.csv')
df.sample(5)

df.dtypes

df.shape

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

normalized_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

normalized_df.sample(5)

normalized_df.shape

import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import GridSearchCV

svc_params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.1, 1]
}

model = keras.Sequential([
    # Hidden Layers
    keras.layers.Dense(64, input_shape=(45,), activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    #keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(4, activation='relu'),
    #keras.layers.Dense(2, activation='relu'),

    # Output Layer
    keras.layers.Dense(1, activation='sigmoid')
])

X = normalized_df.drop('Attack', axis='columns')
y = normalized_df['Attack']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.summary()

model.fit(X_train, y_train, epochs=100)

model.evaluate(X_test, y_test)

yp = model.predict(X_test)
yp[:5]

y_test[:5]

y_pred = []

for element in yp:
  if element > 0.5:
    y_pred.append(1)
  else:
    y_pred.append(0)

y_pred[:5]

from sklearn.metrics import confusion_matrix, classification_report

#print(classification_report(y_test, y_pred))

# Check for NaNs in y_test and handle them
if np.isnan(y_test).any():
    print("Warning: y_test contains NaN values. Handling them...")
    # Option 1: Remove rows with NaNs (if applicable)
    # y_test_clean = y_test[~np.isnan(y_test)]
    # y_pred_clean = y_pred[~np.isnan(y_test)]  # Adjust y_pred accordingly

    # Option 2: Impute NaNs with a suitable value (e.g., mean, median)
    y_test_clean = np.nan_to_num(y_test, nan=np.nanmedian(y_test))

    print(classification_report(y_test_clean, y_pred))  # Use cleaned data
else:
    print(classification_report(y_test, y_pred))

import seaborn as sn
cm = tf.math.confusion_matrix(labels=y_test, predictions=y_pred)

plt.figure(figsize=(10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicited')
plt.ylabel('Truth')

import seaborn as sn
import tensorflow as tf
import numpy as np

# Assuming y_test contains negative values and you want to shift them to be non-negative
y_test_non_negative = y_test - np.min(y_test)

cm = tf.math.confusion_matrix(labels=y_test_non_negative, predictions=y_pred)

plt.figure(figsize=(10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

df['Attack'].value_counts()

# 4. Get predicted probabilities for the positive class (class 1)
y_probs = model.predict(X_test)

# 5. Calculate FPR, TPR, and thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_probs)

# 6. Calculate the Area Under the Curve (AUC)
auc = roc_auc_score(y_test, y_probs)

# 7. Plot the ROC Curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') # Diagonal line (random guess)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()